# The Xdebug image is a simple wrapper of wordpress:latest
FROM andreccosta/wordpress-xdebug

# Use development settings for PHP
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
