version: "3.7"
services:
  db:
    image: postgres:11
    volumes:
      - db_data:/var/lib/postgresql/data/
    restart: on-failure
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  db_admin:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 3001:8080
    environment: 
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_DB_HOST: db
      ADMINER_DEFAULT_DB_NAME: $POSTGRES_DB
  mail:
    image: maildev/maildev
    ports:
      - "3002:80"
  site:
    image: node:lts-alpine
    depends_on:
      - db
      - mail
    ports:
      - "3000:3000"
      - "9229:9229"
    restart: unless-stopped
    working_dir: /opt/node_app/app
    volumes:
      - .:/opt/node_app/app
    command: ./node_modules/.bin/nodemon --inspect=0.0.0.0:9229 index.js
    environment:
      PORT: 3000
      NODE_ENV: $NODE_ENV
      DB_HOST: db
      DB_PORT: 5432
      DB_ADMIN_PORT: 3001
      DB_USER: $POSTGRES_USER
      DB_PASSWORD: $POSTGRES_PASSWORD
      DB_NAME: $POSTGRES_DB
      MAIL_HOST: mail
      MAIL_PORT: 25
      MAIL_ADMIN_PORT: 3002
volumes:
  db_data: